SOURCES:
  ACM:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: acm

  SCIENCEDIRECT:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: ScienceDirect

  IEEE:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: ieee

DADOS_EXPORT:
  # yaml, csv, json, xml, all
  nome_do_arquivo: arquivos_exportados/bib_convertido
  formato_export: all

FILTERS:
  # padrão : Title, keywords, abstract, year, type_publication, doi, JIR, SJR
  cols_to_show: [Title, keywords, abstract, year, type_publication, doi, JIR, SJR]
