SOURCES:
  ACM:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: acm

  SCIENCEDIRECT:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: ScienceDirect

  IEEE:
    directory: /mnt/c/Users/GUSTAVO/Desktop/MBA_IMPACTA/Python/bibtex/arquivos_bibtex/
    namestring: ieee

DADOS_EXPORT:
  # yaml, csv, json, xml, all
  nome_do_arquivo: arquivos_exportados/bib_convertido
  formato_export: all

FILTERS:
  # se quer filtros ou não - yes or no
  active: 'no'
  # padrão : Title, keywords, abstract, year, type_publication, doi, JIR, SJR, journal
  cols_to_show: [Title, author, keywords, journal, abstract, year, type_publication, doi, JIR, SJR]
  # text - o que você quer buscar, 1 palavra simples (big) ou composta (big data) por vez (obrigatório)
  # cond - como vc quer buscar, and ou or (obrigatório) 
  # tipo_comp - tipo de comparação, pode ser >, <, >=, <= ou == 
  values_to_filter:
    Title:
      text:
      cond:
    keywords: 
      text:
      cond:
    abstract:
      text:
      cond: 
    year:
      text: 2020
      tipo_comp: '=='
      cond: and
    type_publication:
      text:
      cond:
    doi: 
      text:
      cond:
    JIR: 
      text: 2
      tipo_comp: '>='
      cond: and
    SJR:
      text: 2
      tipo_comp: '>='
      cond: and

SEARCH:
  api_or_bibtex: api
  string_to_search: data quality 